config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  namespace :api do

  resources :fornecedores
  resources :cargos

end
  get '*path', to: 'pages#index', via: :all 

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cargo.rb
class Cargo < ApplicationRecord
  belongs_to :fornecedor
end

app/models/fornecedor.rb
class Fornecedor < ApplicationRecord
    has_one :cargo
end

app/controllers/api/cargos_controller.rb
module Api
  
class CargosController < ApplicationController
  
  protect_from_forgery with: :null_session
  # GET /cargos or /cargos.json
  
  def index 
    cargos = Cargo.all
    render json: CargoSerializer.new(cargos).serialized_json

  end



 def create
    cargo = Cargo.new(cargo_params)

    if cargo.save
      render json: CargoSerializer.new(cargo).serialized_json
    else
      render json: {error: cargo.errors.messages}, status: 422 
    end
  end

  def destroy
    cargo = Cargo.find(params[:id])

    if cargo.destroy
      head :no_content
    else
      render json: {error: cargo.errors.messages}, status: 422 
    end
  end



  private 
    # Use callbacks to share common setup or constraints between actions.
    def set_cargo
      @cargo = Cargo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cargo_params
      params.require(:cargo).permit(:descricao, :atividade, :fornecedor_id)
    end
end
end

app/controllers/api/fornecedores_controller.rb
module Api
class FornecedoresController < ApplicationController
  
  protect_from_forgery with: :null_session
  # GET /fornecedores or /fornecedores.json
  def index
    @fornecedores = Fornecedor.all

   render json: FornecedorSerializer.new(@fornecedores, options).serialized_json
  end

  # GET /fornecedores/1 or /fornecedores/1.json
  def show  
    fornecedor = Fornecedor.find_by(id: params[:id])
    render json: FornecedorSerializer.new(fornecedor, options).serialized_json
  end

  # GET /fornecedores/new
  def new
    @fornecedor = Fornecedor.new
  end


  # POST /fornecedores or /fornecedores.json
  def create
    @fornecedor = Fornecedor.new(fornecedor_params)

    
      if @fornecedor.save
       
        render json: FornecedorSerializer.new(@fornecedores).serialized_json
      else
       
        render json: {error: fornecedor.errors.messages }, status: 422 
      end
    
  end

  # PATCH/PUT /fornecedores/1 or /fornecedores/1.json
  def update
       fornecedor = Fornecedor.find_by(id: params[:id])
      if fornecedor.update(fornecedor_params)
        
        render json: FornecedorSerializer.new(@fornecedores).serialized_json
      else
       
        render json: {error: fornecedor.errors.messages }, status: 422
      end
    
  end

  # DELETE /fornecedores/1 or /fornecedores/1.json
  def destroy
        fornecedor = Fornecedor.find_by(id: params[:id])

      if fornecedor.destroy
        head :no_content 
      else 
        render json: {error: fornecedor.errors.messages }, status: 422
    
  end
end

  

  private
    # Use callbacks to share common setup or constraints between actions.
    

    # Only allow a list of trusted parameters through.
    def fornecedor_params
      params.require(:fornecedor).permit(:nome, :sobrenome, :dataDeNascimento, :dataDeAdmissao, :salario)
    end

    def options 
      @options ||= {include: %i[cargo]}
    end



end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def index 
    
    end 

end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cargos_helper.rb
module CargosHelper
end

app/helpers/fornecedores_helper.rb
module FornecedoresHelper
end

app/views/cargos/_form.html.erb
<%= form_with(model: cargo) do |form| %>
  <% if cargo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cargo.errors.count, "error") %> prohibited this cargo from being saved:</h2>

      <ul>
        <% cargo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :descricao %>
    <%= form.text_field :descricao %>
  </div>

  <div class="field">
    <%= form.label :atividade %>
    <%= form.text_field :atividade %>
  </div>

  <div class="field">
    <%= form.label :fornecedor_id %>
    <%= form.text_field :fornecedor_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cargos/edit.html.erb
<h1>Editing Cargo</h1>

<%= render 'form', cargo: @cargo %>

<%= link_to 'Show', @cargo %> |
<%= link_to 'Back', cargos_path %>

app/views/cargos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cargos</h1>

<table>
  <thead>
    <tr>
      <th>Descricao</th>
      <th>Atividade</th>
      <th>Fornecedor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cargos.each do |cargo| %>
      <tr>
        <td><%= cargo.descricao %></td>
        <td><%= cargo.atividade %></td>
        <td><%= cargo.fornecedor_id %></td>
        <td><%= link_to 'Show', cargo %></td>
        <td><%= link_to 'Edit', edit_cargo_path(cargo) %></td>
        <td><%= link_to 'Destroy', cargo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cargo', new_cargo_path %>

app/views/cargos/new.html.erb
<h1>New Cargo</h1>

<%= render 'form', cargo: @cargo %>

<%= link_to 'Back', cargos_path %>

app/views/cargos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Descricao:</strong>
  <%= @cargo.descricao %>
</p>

<p>
  <strong>Atividade:</strong>
  <%= @cargo.atividade %>
</p>

<p>
  <strong>Fornecedor:</strong>
  <%= @cargo.fornecedor_id %>
</p>

<%= link_to 'Edit', edit_cargo_path(@cargo) %> |
<%= link_to 'Back', cargos_path %>

app/views/fornecedores/_form.html.erb
<%= form_with(model: fornecedor) do |form| %>
  <% if fornecedor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fornecedor.errors.count, "error") %> prohibited this fornecedor from being saved:</h2>

      <ul>
        <% fornecedor.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :sobrenome %>
    <%= form.text_field :sobrenome %>
  </div>

  <div class="field">
    <%= form.label :dataDeNascimento %>
    <%= form.text_field :dataDeNascimento %>
  </div>

  <div class="field">
    <%= form.label :dataDeAdmissao %>
    <%= form.text_field :dataDeAdmissao %>
  </div>

  <div class="field">
    <%= form.label :salario %>
    <%= form.text_field :salario %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
  

<p id="notice"><%= notice %></p>

<h1>Fornecedores</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Sobrenome</th>
      <th>Datadenascimento</th>
      <th>Datadeadmissao</th>
      <th>Salario</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fornecedores.each do |fornecedor| %>
      <tr>
        <td><%= fornecedor.nome %></td>
        <td><%= fornecedor.sobrenome %></td>
        <td><%= fornecedor.dataDeNascimento %></td>
        <td><%= fornecedor.dataDeAdmissao %></td>
        <td><%= fornecedor.salario %></td>
        <td><%= link_to 'Show', fornecedor %></td>
        <td><%= link_to 'Edit', edit_fornecedor_path(fornecedor) %></td>
        <td><%= link_to 'Destroy', fornecedor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fornecedor', new_fornecedor_path %>
  
  
<% end %>

app/views/fornecedores/edit.html.erb
<h1>Editing Fornecedor</h1>

<%= render 'form', fornecedor: @fornecedor %>

<%= link_to 'Show', @fornecedor %> |
<%= link_to 'Back', fornecedores_path %>

app/views/fornecedores/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Fornecedores</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Sobrenome</th>
      <th>Datadenascimento</th>
      <th>Datadeadmissao</th>
      <th>Salario</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fornecedores.each do |fornecedor| %>
      <tr>
        <td><%= fornecedor.nome %></td>
        <td><%= fornecedor.sobrenome %></td>
        <td><%= fornecedor.dataDeNascimento %></td>
        <td><%= fornecedor.dataDeAdmissao %></td>
        <td><%= fornecedor.salario %></td>
        <td><%= link_to 'Show', fornecedor %></td>
        <td><%= link_to 'Edit', edit_fornecedor_path(fornecedor) %></td>
        <td><%= link_to 'Destroy', fornecedor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fornecedor', new_fornecedor_path %>

app/views/fornecedores/new.html.erb
<h1>New Fornecedor</h1>

<%= render 'form', fornecedor: @fornecedor %>

<%= link_to 'Back', fornecedores_path %>

app/views/fornecedores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @fornecedor.nome %>
</p>

<p>
  <strong>Sobrenome:</strong>
  <%= @fornecedor.sobrenome %>
</p>

<p>
  <strong>Datadenascimento:</strong>
  <%= @fornecedor.dataDeNascimento %>
</p>

<p>
  <strong>Datadeadmissao:</strong>
  <%= @fornecedor.dataDeAdmissao %>
</p>

<p>
  <strong>Salario:</strong>
  <%= @fornecedor.salario %>
</p>

<%= link_to 'Edit', edit_fornecedor_path(@fornecedor) %> |
<%= link_to 'Back', fornecedores_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CrudApi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
  
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application'%>
    <%= javascript_pack_tag 'index' %> 
  </head>

  <body>
    <%= yield %>
  </body>
</html>